-- MySQL dump 10.13  Distrib 8.0.45, for Win64 (x86_64)
--
-- Host: localhost    Database: payroll_db
-- ------------------------------------------------------
-- Server version	8.0.45

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `attendance`
--

DROP TABLE IF EXISTS `attendance`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `attendance` (
  `attendanceId` int NOT NULL AUTO_INCREMENT,
  `staffId` int NOT NULL,
  `companyId` int NOT NULL,
  `shiftAssignmentId` int DEFAULT NULL,
  `shiftTypeId` int DEFAULT NULL,
  `attendanceDate` date NOT NULL,
  `scheduledStartTime` time DEFAULT NULL COMMENT 'Scheduled shift start time',
  `scheduledEndTime` time DEFAULT NULL COMMENT 'Scheduled shift end time',
  `firstCheckIn` datetime DEFAULT NULL COMMENT 'First actual check-in timestamp',
  `lastCheckOut` datetime DEFAULT NULL COMMENT 'Last actual check-out timestamp',
  `totalCheckIns` int NOT NULL DEFAULT '0',
  `totalCheckOuts` int NOT NULL DEFAULT '0',
  `workingHours` decimal(5,2) DEFAULT NULL COMMENT 'Calculated effective working hours',
  `breakHours` decimal(5,2) DEFAULT '0.00',
  `overtimeHours` decimal(5,2) DEFAULT '0.00',
  `overtimeRequestedHours` decimal(5,2) DEFAULT '0.00' COMMENT 'System calculated OT hours after shift end when greater than threshold',
  `overtimeApprovedHours` decimal(5,2) DEFAULT '0.00' COMMENT 'Admin approved payable OT hours',
  `overtimeStatus` enum('None','Pending','Approved','Rejected') NOT NULL DEFAULT 'None',
  `overtimeRemarks` text,
  `attendanceStatus` varchar(100) NOT NULL DEFAULT 'Present' COMMENT 'Free-text status (e.g., "Present", "Permission", "Leave - Sick Leave")',
  `isLate` tinyint(1) DEFAULT '0',
  `lateByMinutes` int DEFAULT '0',
  `isEarlyExit` tinyint(1) DEFAULT '0',
  `earlyExitMinutes` int DEFAULT '0',
  `isHoliday` tinyint(1) DEFAULT '0',
  `isWeekOff` tinyint(1) DEFAULT '0',
  `autoGenerated` tinyint(1) DEFAULT '0' COMMENT 'Auto-generated by system (e.g. default absent)',
  `remarks` text,
  `approvedBy` int DEFAULT NULL,
  `approvedAt` datetime DEFAULT NULL,
  `overtimeApprovedBy` int DEFAULT NULL,
  `overtimeApprovedAt` datetime DEFAULT NULL,
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`attendanceId`),
  UNIQUE KEY `unique_employee_attendance_date` (`staffId`,`attendanceDate`),
  KEY `idx_company_attendance_date` (`companyId`,`attendanceDate`),
  KEY `idx_attendance_status` (`attendanceStatus`),
  KEY `idx_shift_type` (`shiftTypeId`),
  KEY `idx_approved_by` (`approvedBy`),
  KEY `idx_company_overtime_status` (`companyId`,`overtimeStatus`),
  KEY `shiftAssignmentId` (`shiftAssignmentId`),
  KEY `overtimeApprovedBy` (`overtimeApprovedBy`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `attendance_ibfk_10` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `attendance_ibfk_11` FOREIGN KEY (`shiftAssignmentId`) REFERENCES `shift_assignments` (`shiftAssignmentId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `attendance_ibfk_12` FOREIGN KEY (`shiftTypeId`) REFERENCES `shift_types` (`shiftTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `attendance_ibfk_13` FOREIGN KEY (`approvedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `attendance_ibfk_14` FOREIGN KEY (`overtimeApprovedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `attendance_ibfk_15` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `attendance_ibfk_16` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `attendance_ibfk_9` FOREIGN KEY (`staffId`) REFERENCES `staff_details` (`staffId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `attendance`
--

LOCK TABLES `attendance` WRITE;
/*!40000 ALTER TABLE `attendance` DISABLE KEYS */;
/*!40000 ALTER TABLE `attendance` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `biometric_devices`
--

DROP TABLE IF EXISTS `biometric_devices`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `biometric_devices` (
  `deviceId` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL COMMENT 'Device name / friendly name (e.g. "Main Gate Biometric")',
  `deviceIp` varchar(45) NOT NULL COMMENT 'IP address of the biometric device',
  `location` varchar(150) NOT NULL COMMENT 'Physical location / branch / floor / department',
  `status` enum('Active','Inactive','Maintenance','Offline') NOT NULL DEFAULT 'Active' COMMENT 'Current operational status of the device',
  `isAutoSyncEnabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Enable/disable automatic attendance sync (e.g. every 5–15 minutes)',
  `companyId` int NOT NULL,
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`deviceId`),
  UNIQUE KEY `deviceIp` (`deviceIp`),
  UNIQUE KEY `unique_company_device_ip` (`companyId`,`deviceIp`),
  UNIQUE KEY `deviceIp_2` (`deviceIp`),
  UNIQUE KEY `deviceIp_3` (`deviceIp`),
  KEY `idx_device_status` (`status`),
  KEY `idx_company_status` (`companyId`,`status`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `biometric_devices_ibfk_4` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `biometric_devices_ibfk_5` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `biometric_devices_ibfk_6` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `biometric_devices`
--

LOCK TABLES `biometric_devices` WRITE;
/*!40000 ALTER TABLE `biometric_devices` DISABLE KEYS */;
/*!40000 ALTER TABLE `biometric_devices` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `biometric_punches`
--

DROP TABLE IF EXISTS `biometric_punches`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `biometric_punches` (
  `punchId` int NOT NULL AUTO_INCREMENT,
  `staffId` int NOT NULL,
  `biometricDeviceId` int NOT NULL,
  `biometricNumber` varchar(50) NOT NULL COMMENT 'Enrollment ID / Biometric Number from device',
  `punchTimestamp` datetime NOT NULL COMMENT 'Exact timestamp when punch was recorded',
  `punchDate` date NOT NULL COMMENT 'Date part extracted for easier querying/indexing',
  `status` enum('Valid','Invalid','Duplicate','Pending') NOT NULL DEFAULT 'Valid' COMMENT 'Validation status of this punch record',
  `remarks` text,
  `companyId` int NOT NULL,
  `createdBy` int DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`punchId`),
  KEY `idx_employee_punch_date` (`staffId`,`punchDate`),
  KEY `idx_employee_timestamp` (`staffId`,`punchTimestamp`),
  KEY `idx_company_date` (`companyId`,`punchDate`),
  KEY `idx_biometric_number_device` (`biometricNumber`,`biometricDeviceId`),
  KEY `idx_device_timestamp` (`biometricDeviceId`,`punchTimestamp`),
  KEY `idx_status` (`status`),
  KEY `createdBy` (`createdBy`),
  CONSTRAINT `biometric_punches_ibfk_5` FOREIGN KEY (`staffId`) REFERENCES `staff_details` (`staffId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `biometric_punches_ibfk_6` FOREIGN KEY (`biometricDeviceId`) REFERENCES `biometric_devices` (`deviceId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `biometric_punches_ibfk_7` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `biometric_punches_ibfk_8` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `biometric_punches`
--

LOCK TABLES `biometric_punches` WRITE;
/*!40000 ALTER TABLE `biometric_punches` DISABLE KEYS */;
/*!40000 ALTER TABLE `biometric_punches` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `buses`
--

DROP TABLE IF EXISTS `buses`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `buses` (
  `busId` int NOT NULL AUTO_INCREMENT,
  `busNumber` varchar(20) NOT NULL COMMENT 'Registration number / Bus number plate (e.g. MH-01-AB-1234)',
  `name` varchar(100) DEFAULT NULL COMMENT 'Friendly name (e.g. "Route 1 Express", "Employee Shuttle A")',
  `busDriverName` varchar(100) DEFAULT NULL COMMENT 'Name of the current/assigned driver',
  `location` varchar(150) DEFAULT NULL COMMENT 'Base location / depot / starting point',
  `busRouteDetails` varchar(500) DEFAULT NULL COMMENT 'Route description or key stops',
  `status` enum('Active','Inactive','Maintenance','Out of Service') NOT NULL DEFAULT 'Active' COMMENT 'Current operational status of the bus',
  `companyId` int NOT NULL,
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`busId`),
  UNIQUE KEY `busNumber` (`busNumber`),
  UNIQUE KEY `unique_company_bus_number` (`companyId`,`busNumber`),
  UNIQUE KEY `busNumber_2` (`busNumber`),
  UNIQUE KEY `busNumber_3` (`busNumber`),
  KEY `idx_bus_status` (`status`),
  KEY `idx_company_status` (`companyId`,`status`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `buses_ibfk_4` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `buses_ibfk_5` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `buses_ibfk_6` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `buses`
--

LOCK TABLES `buses` WRITE;
/*!40000 ALTER TABLE `buses` DISABLE KEYS */;
/*!40000 ALTER TABLE `buses` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `companies`
--

DROP TABLE IF EXISTS `companies`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `companies` (
  `companyId` int NOT NULL AUTO_INCREMENT,
  `companyName` varchar(150) NOT NULL COMMENT 'Full legal/official name of the company',
  `companyAcr` varchar(20) NOT NULL COMMENT 'Short acronym/code (e.g. "ABCPL", "XYZHR")',
  `logo` varchar(500) DEFAULT NULL COMMENT 'Path/URL to company logo',
  `registrationNumber` varchar(50) DEFAULT NULL COMMENT 'Company registration / CIN number',
  `pan` varchar(10) DEFAULT NULL COMMENT 'Permanent Account Number (PAN)',
  `gst` varchar(15) DEFAULT NULL COMMENT 'GST Identification Number',
  `tin` varchar(20) DEFAULT NULL COMMENT 'Tax Identification Number (if applicable)',
  `phone` varchar(15) DEFAULT NULL,
  `email` varchar(150) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `addresses` json DEFAULT NULL COMMENT 'JSON object with registered/office/branch addresses',
  `bankName` varchar(100) DEFAULT NULL,
  `bankAccountNumber` varchar(50) DEFAULT NULL,
  `bankIfscCode` varchar(11) DEFAULT NULL,
  `financialYearStart` date DEFAULT NULL,
  `financialYearEnd` date DEFAULT NULL,
  `permissionHoursPerMonth` int DEFAULT '0' COMMENT 'Monthly permission hours quota for employees',
  `status` enum('Active','Inactive','Suspended') NOT NULL DEFAULT 'Active',
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`companyId`),
  UNIQUE KEY `companyAcr` (`companyAcr`),
  UNIQUE KEY `unique_company_acr` (`companyAcr`),
  UNIQUE KEY `unique_company_name` (`companyName`),
  UNIQUE KEY `companyAcr_2` (`companyAcr`),
  UNIQUE KEY `companyAcr_3` (`companyAcr`),
  UNIQUE KEY `registrationNumber` (`registrationNumber`),
  UNIQUE KEY `pan` (`pan`),
  UNIQUE KEY `gst` (`gst`),
  UNIQUE KEY `registrationNumber_2` (`registrationNumber`),
  UNIQUE KEY `pan_2` (`pan`),
  UNIQUE KEY `gst_2` (`gst`),
  UNIQUE KEY `registrationNumber_3` (`registrationNumber`),
  UNIQUE KEY `pan_3` (`pan`),
  UNIQUE KEY `gst_3` (`gst`),
  KEY `idx_company_status` (`status`),
  KEY `idx_company_id` (`companyId`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `companies_ibfk_1` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `companies_ibfk_2` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `companies`
--

LOCK TABLES `companies` WRITE;
/*!40000 ALTER TABLE `companies` DISABLE KEYS */;
/*!40000 ALTER TABLE `companies` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `departments`
--

DROP TABLE IF EXISTS `departments`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `departments` (
  `departmentId` int NOT NULL AUTO_INCREMENT,
  `departmentName` varchar(100) NOT NULL COMMENT 'Full name of the department (e.g. "Human Resources", "Finance & Accounts")',
  `departmentAcr` varchar(10) NOT NULL COMMENT 'Short code / abbreviation (e.g. HR, FIN, IT, OPS)',
  `priorityOrder` int NOT NULL DEFAULT '0' COMMENT 'Display priority (lower comes first)',
  `status` enum('Active','Inactive','Archived') NOT NULL DEFAULT 'Active' COMMENT 'Current status of the department',
  `companyId` int NOT NULL,
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`departmentId`),
  UNIQUE KEY `unique_company_department_name` (`companyId`,`departmentName`),
  UNIQUE KEY `unique_company_department_acr` (`companyId`,`departmentAcr`),
  KEY `idx_company_department_status` (`companyId`,`status`),
  KEY `idx_department_status` (`status`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `departments_ibfk_4` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `departments_ibfk_5` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `departments_ibfk_6` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `departments`
--

LOCK TABLES `departments` WRITE;
/*!40000 ALTER TABLE `departments` DISABLE KEYS */;
/*!40000 ALTER TABLE `departments` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `designations`
--

DROP TABLE IF EXISTS `designations`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `designations` (
  `designationId` int NOT NULL AUTO_INCREMENT,
  `designationName` varchar(100) NOT NULL COMMENT 'Full name of the designation/post (e.g. "Senior Software Engineer", "Finance Manager")',
  `designationAcr` varchar(10) NOT NULL COMMENT 'Short code/abbreviation (e.g. "SSE", "AM", "TL", "FM")',
  `priorityOrder` int NOT NULL DEFAULT '0' COMMENT 'Display priority (lower comes first)',
  `status` enum('Active','Inactive','Archived') NOT NULL DEFAULT 'Active' COMMENT 'Current status of the designation',
  `companyId` int NOT NULL,
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`designationId`),
  UNIQUE KEY `unique_company_designation_name` (`companyId`,`designationName`),
  UNIQUE KEY `unique_company_designation_acr` (`companyId`,`designationAcr`),
  KEY `idx_company_designation_status` (`companyId`,`status`),
  KEY `idx_designation_status` (`status`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `designations_ibfk_4` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `designations_ibfk_5` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `designations_ibfk_6` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `designations`
--

LOCK TABLES `designations` WRITE;
/*!40000 ALTER TABLE `designations` DISABLE KEYS */;
/*!40000 ALTER TABLE `designations` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `employee_grades`
--

DROP TABLE IF EXISTS `employee_grades`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `employee_grades` (
  `employeeGradeId` int NOT NULL AUTO_INCREMENT,
  `employeeGradeName` varchar(255) NOT NULL COMMENT 'Full name of the grade (e.g. "Grade A - Senior", "Teaching Faculty Level 1")',
  `employeeGradeAcr` varchar(10) NOT NULL COMMENT 'Short code/abbreviation (e.g. "GA", "L1", "TCH-A")',
  `status` enum('Active','Inactive') NOT NULL DEFAULT 'Active',
  `companyId` int NOT NULL,
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`employeeGradeId`),
  UNIQUE KEY `unique_company_grade_name` (`companyId`,`employeeGradeName`),
  UNIQUE KEY `unique_company_grade_acr` (`companyId`,`employeeGradeAcr`),
  KEY `idx_company_grade_status` (`companyId`,`status`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `employee_grades_ibfk_4` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `employee_grades_ibfk_5` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `employee_grades_ibfk_6` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `employee_grades`
--

LOCK TABLES `employee_grades` WRITE;
/*!40000 ALTER TABLE `employee_grades` DISABLE KEYS */;
/*!40000 ALTER TABLE `employee_grades` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `employee_loans`
--

DROP TABLE IF EXISTS `employee_loans`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `employee_loans` (
  `employeeLoanId` int NOT NULL AUTO_INCREMENT,
  `staffId` int NOT NULL,
  `loanType` enum('Personal Loan','Home Loan','Vehicle Loan','Education Loan','Emergency Loan','Advance') NOT NULL DEFAULT 'Personal Loan',
  `loanAmount` decimal(10,2) NOT NULL COMMENT 'Total loan amount sanctioned',
  `interestRate` decimal(5,2) DEFAULT '0.00' COMMENT 'Interest rate percentage (if applicable)',
  `sanctionDate` date NOT NULL COMMENT 'Date when loan was sanctioned',
  `startDate` date NOT NULL COMMENT 'Date from which deduction starts',
  `numberOfInstallments` int NOT NULL COMMENT 'Total number of installments',
  `installmentAmount` decimal(10,2) NOT NULL COMMENT 'Amount to be deducted per month',
  `paidInstallments` int NOT NULL DEFAULT '0' COMMENT 'Number of installments paid so far',
  `paidAmount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Total amount paid so far',
  `status` enum('pending','active','completed','cancelled') NOT NULL DEFAULT 'pending' COMMENT 'Current status of the loan',
  `approvedBy` int DEFAULT NULL COMMENT 'Employee ID who approved the loan',
  `approvedDate` date DEFAULT NULL COMMENT 'Date when loan was approved',
  `remarks` text COMMENT 'Additional remarks or notes',
  `reason` text COMMENT 'Reason for taking the loan',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  PRIMARY KEY (`employeeLoanId`),
  KEY `employee_loans_staff_id` (`staffId`),
  KEY `employee_loans_status` (`status`),
  KEY `employee_loans_sanction_date` (`sanctionDate`),
  KEY `approvedBy` (`approvedBy`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `employee_loans_ibfk_5` FOREIGN KEY (`staffId`) REFERENCES `staff_details` (`staffId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `employee_loans_ibfk_6` FOREIGN KEY (`approvedBy`) REFERENCES `staff_details` (`staffId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `employee_loans_ibfk_7` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `employee_loans_ibfk_8` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `employee_loans`
--

LOCK TABLES `employee_loans` WRITE;
/*!40000 ALTER TABLE `employee_loans` DISABLE KEYS */;
/*!40000 ALTER TABLE `employee_loans` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `employee_salary_components`
--

DROP TABLE IF EXISTS `employee_salary_components`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `employee_salary_components` (
  `employeeSalaryComponentid` int NOT NULL AUTO_INCREMENT,
  `employeeSalaryMasterId` int NOT NULL,
  `componentId` int NOT NULL,
  `componentName` varchar(255) NOT NULL COMMENT 'Component name stored for historical reference',
  `componentCode` varchar(255) NOT NULL COMMENT 'Component code stored for historical reference',
  `componentType` enum('Earning','Deduction') NOT NULL,
  `valueType` enum('Fixed','Percentage','Formula') NOT NULL COMMENT 'How this component is calculated',
  `fixedAmount` decimal(10,2) DEFAULT NULL COMMENT 'Used when valueType is Fixed',
  `percentageValue` decimal(5,2) DEFAULT NULL COMMENT 'Used when valueType is Percentage (e.g., 40 for 40%)',
  `percentageBase` varchar(50) DEFAULT NULL COMMENT 'Component code to calculate percentage on (e.g., BASIC, GROSS)',
  `formulaId` int DEFAULT NULL,
  `formulaExpression` text COMMENT 'Stored formula expression for historical reference',
  `calculatedAmount` decimal(10,2) NOT NULL COMMENT 'Final monthly amount for this component',
  `annualAmount` decimal(12,2) NOT NULL COMMENT 'Annual amount (calculatedAmount * 12)',
  `isStatutory` tinyint(1) DEFAULT '0' COMMENT 'Whether this is a statutory component (PF, ESI, etc.)',
  `isTaxable` tinyint(1) DEFAULT '1' COMMENT 'Whether this component is taxable',
  `affectsGrossSalary` tinyint(1) DEFAULT '1' COMMENT 'Whether this affects gross salary calculation',
  `affectsNetSalary` tinyint(1) DEFAULT '1' COMMENT 'Whether this affects net salary calculation',
  `displayOrder` int DEFAULT '0' COMMENT 'Order for display in payslip',
  `effectiveFrom` date NOT NULL COMMENT 'Date from which this component value is effective',
  `effectiveTo` date DEFAULT NULL COMMENT 'Date until which this component value is effective (NULL = ongoing)',
  `status` enum('Active','Inactive') NOT NULL DEFAULT 'Active',
  `remarks` text,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `salaryComponentId` int DEFAULT NULL,
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  PRIMARY KEY (`employeeSalaryComponentid`),
  KEY `employee_salary_components_employee_salary_master_id` (`employeeSalaryMasterId`),
  KEY `employee_salary_components_component_id` (`componentId`),
  KEY `employee_salary_components_component_code` (`componentCode`),
  KEY `employee_salary_components_status` (`status`),
  KEY `employee_salary_components_effective_from` (`effectiveFrom`),
  KEY `employee_salary_components_effective_to` (`effectiveTo`),
  KEY `formulaId` (`formulaId`),
  KEY `salaryComponentId` (`salaryComponentId`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `employee_salary_components_ibfk_10` FOREIGN KEY (`salaryComponentId`) REFERENCES `salary_components` (`salaryComponentId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `employee_salary_components_ibfk_11` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `employee_salary_components_ibfk_12` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `employee_salary_components_ibfk_7` FOREIGN KEY (`employeeSalaryMasterId`) REFERENCES `employee_salary_masters` (`employeeSalaryMasterId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `employee_salary_components_ibfk_8` FOREIGN KEY (`componentId`) REFERENCES `salary_components` (`salaryComponentId`) ON DELETE RESTRICT,
  CONSTRAINT `employee_salary_components_ibfk_9` FOREIGN KEY (`formulaId`) REFERENCES `formulas` (`formulaId`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `employee_salary_components`
--

LOCK TABLES `employee_salary_components` WRITE;
/*!40000 ALTER TABLE `employee_salary_components` DISABLE KEYS */;
/*!40000 ALTER TABLE `employee_salary_components` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `employee_salary_masters`
--

DROP TABLE IF EXISTS `employee_salary_masters`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `employee_salary_masters` (
  `employeeSalaryMasterId` int NOT NULL AUTO_INCREMENT,
  `staffId` int NOT NULL,
  `companyId` int NOT NULL,
  `effectiveFrom` date NOT NULL COMMENT 'Date from which this salary structure is effective',
  `effectiveTo` date DEFAULT NULL COMMENT 'Date until which this salary structure is effective (NULL = current)',
  `basicSalary` decimal(12,2) NOT NULL COMMENT 'Basic salary component',
  `grossSalary` decimal(12,2) NOT NULL COMMENT 'Total of all earnings',
  `totalDeductions` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT 'Total monthly deductions',
  `netSalary` decimal(12,2) NOT NULL COMMENT 'Take home = Gross - Deductions',
  `ctcAnnual` decimal(12,2) NOT NULL COMMENT 'Annual Cost to Company',
  `ctcMonthly` decimal(12,2) NOT NULL COMMENT 'Monthly CTC',
  `revisionType` enum('Initial','Annual_Hike','Promotion','Special_Increment','Correction','Transfer') NOT NULL DEFAULT 'Initial' COMMENT 'Type of salary revision',
  `revisionPercentage` decimal(5,2) DEFAULT NULL COMMENT 'Hike percentage (e.g., 10.50 for 10.5%)',
  `previousSalaryId` int DEFAULT NULL COMMENT 'Reference to previous salary structure (self-reference)',
  `status` enum('Draft','Active','Superseded','Cancelled') NOT NULL DEFAULT 'Active' COMMENT 'Active = current salary, Superseded = replaced by new revision',
  `remarks` text,
  `createdBy` int DEFAULT NULL COMMENT 'User who created this salary record',
  `updatedBy` int DEFAULT NULL COMMENT 'User who last updated this salary record',
  `approvedBy` int DEFAULT NULL COMMENT 'User who approved this salary revision',
  `approvedDate` datetime DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`employeeSalaryMasterId`),
  KEY `idx_employee_effective_from` (`staffId`,`effectiveFrom`),
  KEY `idx_employee_status` (`staffId`,`status`),
  KEY `idx_company_effective_from` (`companyId`,`effectiveFrom`),
  KEY `previousSalaryId` (`previousSalaryId`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  KEY `approvedBy` (`approvedBy`),
  CONSTRAINT `employee_salary_masters_ibfk_10` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `employee_salary_masters_ibfk_11` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `employee_salary_masters_ibfk_12` FOREIGN KEY (`approvedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `employee_salary_masters_ibfk_7` FOREIGN KEY (`staffId`) REFERENCES `staff_details` (`staffId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `employee_salary_masters_ibfk_8` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `employee_salary_masters_ibfk_9` FOREIGN KEY (`previousSalaryId`) REFERENCES `employee_salary_masters` (`employeeSalaryMasterId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `employee_salary_masters`
--

LOCK TABLES `employee_salary_masters` WRITE;
/*!40000 ALTER TABLE `employee_salary_masters` DISABLE KEYS */;
/*!40000 ALTER TABLE `employee_salary_masters` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `formulas`
--

DROP TABLE IF EXISTS `formulas`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `formulas` (
  `formulaId` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL COMMENT 'Formula name for identification (e.g. "Basic + HRA Allowance")',
  `description` text COMMENT 'Description of what this formula calculates',
  `formulaType` enum('Simple','Conditional','Complex') NOT NULL DEFAULT 'Simple' COMMENT 'Type of formula structure',
  `formulaExpression` text NOT NULL COMMENT 'The actual formula expression (e.g., BASIC + HRA * 0.5)',
  `formulaJson` json NOT NULL COMMENT 'JSON structure of formula for visual builder',
  `variables` json DEFAULT NULL COMMENT 'List of component codes/names used in this formula',
  `targetComponentId` int DEFAULT NULL COMMENT 'The salary component this formula calculates',
  `applicableDesignations` json DEFAULT NULL COMMENT 'Array of designation IDs this formula applies to. Empty = all designations.',
  `isActive` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Whether this formula is currently active',
  `validFrom` datetime DEFAULT NULL COMMENT 'Date from which this formula is valid',
  `validTo` datetime DEFAULT NULL COMMENT 'Date until which this formula is valid',
  `priority` int NOT NULL DEFAULT '0' COMMENT 'Execution priority (lower number = higher priority)',
  `companyId` int NOT NULL,
  `createdBy` int DEFAULT NULL COMMENT 'User ID who created this formula',
  `updatedBy` int DEFAULT NULL COMMENT 'User ID who last updated this formula',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`formulaId`),
  KEY `idx_company_active` (`companyId`,`isActive`),
  KEY `idx_target_component` (`targetComponentId`),
  KEY `idx_formula_type_active` (`formulaType`,`isActive`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `formulas_ibfk_5` FOREIGN KEY (`targetComponentId`) REFERENCES `salary_components` (`salaryComponentId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `formulas_ibfk_6` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `formulas_ibfk_7` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `formulas_ibfk_8` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `formulas`
--

LOCK TABLES `formulas` WRITE;
/*!40000 ALTER TABLE `formulas` DISABLE KEYS */;
/*!40000 ALTER TABLE `formulas` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `holiday_plans`
--

DROP TABLE IF EXISTS `holiday_plans`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `holiday_plans` (
  `holidayPlanId` int NOT NULL AUTO_INCREMENT,
  `holidayPlanName` varchar(255) NOT NULL COMMENT 'Name of the holiday plan/year (e.g. "2025 Company Holidays")',
  `startDate` date NOT NULL,
  `endDate` date NOT NULL,
  `status` enum('Active','Inactive') NOT NULL DEFAULT 'Active',
  `companyId` int NOT NULL,
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`holidayPlanId`),
  KEY `idx_company_holiday_period` (`companyId`,`startDate`,`endDate`),
  KEY `idx_holiday_plan_status` (`status`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `holiday_plans_ibfk_4` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `holiday_plans_ibfk_5` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `holiday_plans_ibfk_6` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `holiday_plans`
--

LOCK TABLES `holiday_plans` WRITE;
/*!40000 ALTER TABLE `holiday_plans` DISABLE KEYS */;
/*!40000 ALTER TABLE `holiday_plans` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `holidays`
--

DROP TABLE IF EXISTS `holidays`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `holidays` (
  `holidayId` int NOT NULL AUTO_INCREMENT,
  `holidayDate` date NOT NULL COMMENT 'Date of the holiday or week off',
  `description` varchar(255) NOT NULL COMMENT 'Name/description of the holiday (e.g. "Republic Day", "Diwali")',
  `type` enum('Holiday','Week Off','Optional Holiday') NOT NULL DEFAULT 'Holiday' COMMENT 'Type of day: mandatory holiday or weekly off',
  `holidayPlanId` int NOT NULL,
  `companyId` int NOT NULL,
  `status` enum('Active','Inactive') NOT NULL DEFAULT 'Active',
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`holidayId`),
  UNIQUE KEY `unique_plan_date` (`holidayPlanId`,`holidayDate`),
  KEY `idx_company_holiday_date` (`companyId`,`holidayDate`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `holidays_ibfk_5` FOREIGN KEY (`holidayPlanId`) REFERENCES `holiday_plans` (`holidayPlanId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `holidays_ibfk_6` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `holidays_ibfk_7` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `holidays_ibfk_8` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `holidays`
--

LOCK TABLES `holidays` WRITE;
/*!40000 ALTER TABLE `holidays` DISABLE KEYS */;
/*!40000 ALTER TABLE `holidays` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `leave_allocations`
--

DROP TABLE IF EXISTS `leave_allocations`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `leave_allocations` (
  `leaveAllocationId` int NOT NULL AUTO_INCREMENT,
  `staffId` int NOT NULL,
  `leaveTypeId` int NOT NULL,
  `leavePolicyId` int DEFAULT NULL COMMENT 'The policy from which this allocation was derived',
  `companyId` int NOT NULL,
  `allocatedLeaves` decimal(10,2) NOT NULL DEFAULT '0.00',
  `carryForwardFromPrevious` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Carry forward balance from previous period',
  `usedLeaves` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Leaves used/taken in this period',
  `maxCarryForwardLimit` decimal(10,2) DEFAULT NULL COMMENT 'Maximum days that can be carried forward (per-employee override)',
  `carryForwardExpiryDate` date DEFAULT NULL COMMENT 'Date by which carry forward must be used',
  `isProRated` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Is this allocation pro-rated for mid-year joiner',
  `proRatedDays` decimal(10,2) DEFAULT NULL COMMENT 'Pro-rated allocation for partial period',
  `enableMonthlyAccrual` tinyint(1) NOT NULL DEFAULT '0',
  `monthlyAccrualRate` decimal(10,2) DEFAULT NULL COMMENT 'Leaves to be accrued per month',
  `accrualCondition` enum('first_year','all_employees','grade_based') DEFAULT NULL COMMENT 'Condition for monthly accrual',
  `totalAccruedTillDate` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Total accrued till current date',
  `allowNegativeBalance` tinyint(1) NOT NULL DEFAULT '0',
  `maxNegativeLimit` decimal(10,2) DEFAULT '0.00' COMMENT 'Maximum negative balance allowed',
  `status` enum('Active','Expired','Cancelled') NOT NULL DEFAULT 'Active',
  `allocatedDate` date NOT NULL,
  `effectiveFrom` date NOT NULL,
  `effectiveTo` date NOT NULL,
  `notifyEmployee` tinyint(1) NOT NULL DEFAULT '1',
  `notifyManager` tinyint(1) NOT NULL DEFAULT '0',
  `notes` text,
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`leaveAllocationId`),
  UNIQUE KEY `unique_allocation_per_employee_type_period` (`staffId`,`leaveTypeId`,`effectiveFrom`,`effectiveTo`),
  KEY `leaveTypeId` (`leaveTypeId`),
  KEY `leavePolicyId` (`leavePolicyId`),
  KEY `companyId` (`companyId`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `leave_allocations_ibfk_10` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `leave_allocations_ibfk_11` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `leave_allocations_ibfk_12` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `leave_allocations_ibfk_7` FOREIGN KEY (`staffId`) REFERENCES `staff_details` (`staffId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `leave_allocations_ibfk_8` FOREIGN KEY (`leaveTypeId`) REFERENCES `leave_types` (`leaveTypeId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `leave_allocations_ibfk_9` FOREIGN KEY (`leavePolicyId`) REFERENCES `leave_policies` (`leavePolicyId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `leave_allocations`
--

LOCK TABLES `leave_allocations` WRITE;
/*!40000 ALTER TABLE `leave_allocations` DISABLE KEYS */;
/*!40000 ALTER TABLE `leave_allocations` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `leave_approvals`
--

DROP TABLE IF EXISTS `leave_approvals`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `leave_approvals` (
  `leaveApprovalId` int NOT NULL AUTO_INCREMENT,
  `leaveRequestId` int NOT NULL,
  `approverId` int NOT NULL COMMENT 'Employee ID of the approver',
  `approverLevel` int NOT NULL COMMENT 'Approval level: 1 = Manager, 2 = Dept Head, etc.',
  `approverRole` varchar(100) DEFAULT NULL COMMENT 'Role description: "Reporting Manager", "Department Head", etc.',
  `status` enum('Pending','Approved','Rejected','Forwarded','Skipped') NOT NULL DEFAULT 'Pending',
  `comments` text COMMENT 'Comments provided by approver',
  `actionDate` datetime DEFAULT NULL COMMENT 'Date when action was taken',
  `notificationSent` tinyint(1) NOT NULL DEFAULT '0',
  `notificationSentAt` datetime DEFAULT NULL,
  `emailSent` tinyint(1) NOT NULL DEFAULT '0',
  `emailSentAt` datetime DEFAULT NULL,
  `companyId` int NOT NULL,
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`leaveApprovalId`),
  UNIQUE KEY `unique_request_approver_level` (`leaveRequestId`,`approverLevel`),
  KEY `idx_approver_status` (`approverId`,`status`),
  KEY `idx_leave_request` (`leaveRequestId`),
  KEY `companyId` (`companyId`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `leave_approvals_ibfk_10` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `leave_approvals_ibfk_6` FOREIGN KEY (`leaveRequestId`) REFERENCES `leave_requests` (`leaveRequestId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `leave_approvals_ibfk_7` FOREIGN KEY (`approverId`) REFERENCES `staff_details` (`staffId`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `leave_approvals_ibfk_8` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `leave_approvals_ibfk_9` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `leave_approvals`
--

LOCK TABLES `leave_approvals` WRITE;
/*!40000 ALTER TABLE `leave_approvals` DISABLE KEYS */;
/*!40000 ALTER TABLE `leave_approvals` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `leave_periods`
--

DROP TABLE IF EXISTS `leave_periods`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `leave_periods` (
  `leavePeriodId` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `startDate` date NOT NULL,
  `endDate` date NOT NULL,
  `status` enum('Active','Inactive') NOT NULL DEFAULT 'Active',
  `companyId` int NOT NULL,
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`leavePeriodId`),
  KEY `idx_leave_period_company_status` (`companyId`,`status`),
  KEY `idx_leave_period_company_dates` (`companyId`,`startDate`,`endDate`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `leave_periods_ibfk_4` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `leave_periods_ibfk_5` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `leave_periods_ibfk_6` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `leave_periods`
--

LOCK TABLES `leave_periods` WRITE;
/*!40000 ALTER TABLE `leave_periods` DISABLE KEYS */;
/*!40000 ALTER TABLE `leave_periods` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `leave_policies`
--

DROP TABLE IF EXISTS `leave_policies`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `leave_policies` (
  `leavePolicyId` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL COMMENT 'Policy name (e.g. "Annual Leave Policy - Permanent Staff")',
  `leaveTypeId` int NOT NULL COMMENT 'Foreign key to leave type',
  `accrualFrequency` enum('Monthly','Quarterly','Yearly','On Joining') NOT NULL DEFAULT 'Yearly',
  `maxCarryForward` int NOT NULL DEFAULT '0' COMMENT 'Maximum leaves that can be carried forward to next period',
  `allowEncashment` tinyint(1) NOT NULL DEFAULT '0',
  `encashmentRules` text COMMENT 'Rules or formula for encashment (free text or JSON)',
  `companyId` int NOT NULL,
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  `status` enum('Active','Inactive') NOT NULL DEFAULT 'Active',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`leavePolicyId`),
  UNIQUE KEY `uq_policy_company_name` (`companyId`,`name`),
  KEY `idx_policy_company_leave_type` (`companyId`,`leaveTypeId`),
  KEY `leaveTypeId` (`leaveTypeId`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `leave_policies_ibfk_5` FOREIGN KEY (`leaveTypeId`) REFERENCES `leave_types` (`leaveTypeId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `leave_policies_ibfk_6` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `leave_policies_ibfk_7` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `leave_policies_ibfk_8` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `leave_policies`
--

LOCK TABLES `leave_policies` WRITE;
/*!40000 ALTER TABLE `leave_policies` DISABLE KEYS */;
/*!40000 ALTER TABLE `leave_policies` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `leave_request_histories`
--

DROP TABLE IF EXISTS `leave_request_histories`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `leave_request_histories` (
  `leaveRequestHistoryId` int NOT NULL AUTO_INCREMENT,
  `leaveRequestId` int NOT NULL,
  `action` enum('Created','Submitted','Approved','Rejected','Cancelled','Modified','Withdrawn','Forwarded','Deleted','Restored') NOT NULL,
  `actionBy` int NOT NULL COMMENT 'Employee who performed the action',
  `actionDate` datetime NOT NULL,
  `oldStatus` enum('Draft','Pending','Approved','Rejected','Cancelled','Withdrawn') DEFAULT NULL COMMENT 'Previous status before this action',
  `newStatus` enum('Draft','Pending','Approved','Rejected','Cancelled','Withdrawn') DEFAULT NULL COMMENT 'New status after this action',
  `comments` text COMMENT 'Comments or notes about the action',
  `actionContext` json DEFAULT NULL COMMENT 'Additional context data (changes made, approver level, etc.)',
  `ipAddress` varchar(45) DEFAULT NULL COMMENT 'IP address from which action was taken',
  `userAgent` text COMMENT 'Browser/device information',
  `companyId` int NOT NULL,
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  PRIMARY KEY (`leaveRequestHistoryId`),
  KEY `idx_request_action_date` (`leaveRequestId`,`actionDate`),
  KEY `idx_action_by` (`actionBy`),
  KEY `idx_action_type` (`action`),
  KEY `idx_action_date` (`actionDate`),
  KEY `idx_leave_request` (`leaveRequestId`),
  KEY `companyId` (`companyId`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `leave_request_histories_ibfk_10` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `leave_request_histories_ibfk_6` FOREIGN KEY (`leaveRequestId`) REFERENCES `leave_requests` (`leaveRequestId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `leave_request_histories_ibfk_7` FOREIGN KEY (`actionBy`) REFERENCES `staff_details` (`staffId`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `leave_request_histories_ibfk_8` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `leave_request_histories_ibfk_9` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `leave_request_histories`
--

LOCK TABLES `leave_request_histories` WRITE;
/*!40000 ALTER TABLE `leave_request_histories` DISABLE KEYS */;
/*!40000 ALTER TABLE `leave_request_histories` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `leave_requests`
--

DROP TABLE IF EXISTS `leave_requests`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `leave_requests` (
  `leaveRequestId` int NOT NULL AUTO_INCREMENT,
  `staffId` int NOT NULL,
  `leaveTypeId` int NOT NULL,
  `leaveAllocationId` int DEFAULT NULL COMMENT 'Link to the specific allocation from which this leave is deducted',
  `companyId` int NOT NULL,
  `startDate` date NOT NULL,
  `endDate` date NOT NULL,
  `totalDays` decimal(4,1) NOT NULL DEFAULT '0.0' COMMENT 'Total leave days (can be 0.5 for half day)',
  `leaveCategory` enum('Full Day','Half Day') NOT NULL DEFAULT 'Full Day',
  `halfDayType` enum('First Half','Second Half') DEFAULT NULL COMMENT 'Required if leaveCategory is Half Day',
  `reason` text NOT NULL,
  `hasDocuments` tinyint(1) NOT NULL DEFAULT '0',
  `documentPaths` json DEFAULT NULL COMMENT 'Array of document file paths',
  `contactDuringLeave` varchar(20) DEFAULT NULL COMMENT 'Phone number to contact during leave',
  `addressDuringLeave` text,
  `status` enum('Draft','Pending','Approved','Rejected','Cancelled','Withdrawn') NOT NULL DEFAULT 'Pending',
  `currentApprovalLevel` int NOT NULL DEFAULT '0' COMMENT '0 = not submitted, 1+ = approval levels',
  `maxApprovalLevel` int NOT NULL DEFAULT '1' COMMENT 'Total number of approval levels required',
  `appliedDate` datetime DEFAULT NULL COMMENT 'Date when leave was submitted',
  `submittedBy` int DEFAULT NULL COMMENT 'If applied by HR/Manager on behalf of employee',
  `cancelledAt` datetime DEFAULT NULL,
  `cancelledBy` int DEFAULT NULL,
  `cancellationReason` text,
  `finalApprovedBy` int DEFAULT NULL,
  `finalApprovedAt` datetime DEFAULT NULL,
  `finalRejectedBy` int DEFAULT NULL,
  `finalRejectedAt` datetime DEFAULT NULL,
  `rejectionReason` text,
  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',
  `notes` text COMMENT 'Internal notes by HR/Admin',
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`leaveRequestId`),
  KEY `idx_employee_status` (`staffId`,`status`),
  KEY `idx_company_status` (`companyId`,`status`),
  KEY `idx_date_range` (`startDate`,`endDate`),
  KEY `idx_leave_type` (`leaveTypeId`),
  KEY `idx_leave_request` (`leaveRequestId`),
  KEY `leaveAllocationId` (`leaveAllocationId`),
  KEY `submittedBy` (`submittedBy`),
  KEY `cancelledBy` (`cancelledBy`),
  KEY `finalApprovedBy` (`finalApprovedBy`),
  KEY `finalRejectedBy` (`finalRejectedBy`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `leave_requests_ibfk_11` FOREIGN KEY (`staffId`) REFERENCES `staff_details` (`staffId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `leave_requests_ibfk_12` FOREIGN KEY (`leaveTypeId`) REFERENCES `leave_types` (`leaveTypeId`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `leave_requests_ibfk_13` FOREIGN KEY (`leaveAllocationId`) REFERENCES `leave_allocations` (`leaveAllocationId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `leave_requests_ibfk_14` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `leave_requests_ibfk_15` FOREIGN KEY (`submittedBy`) REFERENCES `staff_details` (`staffId`),
  CONSTRAINT `leave_requests_ibfk_16` FOREIGN KEY (`cancelledBy`) REFERENCES `staff_details` (`staffId`),
  CONSTRAINT `leave_requests_ibfk_17` FOREIGN KEY (`finalApprovedBy`) REFERENCES `staff_details` (`staffId`),
  CONSTRAINT `leave_requests_ibfk_18` FOREIGN KEY (`finalRejectedBy`) REFERENCES `staff_details` (`staffId`),
  CONSTRAINT `leave_requests_ibfk_19` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `leave_requests_ibfk_20` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `leave_requests`
--

LOCK TABLES `leave_requests` WRITE;
/*!40000 ALTER TABLE `leave_requests` DISABLE KEYS */;
/*!40000 ALTER TABLE `leave_requests` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `leave_types`
--

DROP TABLE IF EXISTS `leave_types`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `leave_types` (
  `leaveTypeId` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL COMMENT 'Name of the leave type (e.g. "Sick Leave", "Annual Leave")',
  `leaveTypeName` varchar(255) DEFAULT NULL COMMENT 'Legacy leave type name field kept for backward compatibility',
  `maxAllocationPertype` int DEFAULT NULL,
  `allowApplicationAfterDays` int DEFAULT NULL,
  `minWorkingDaysForLeave` int DEFAULT NULL,
  `description` text COMMENT 'Detailed description or rules for this leave type',
  `isPaid` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether this leave type is paid',
  `isWithoutPay` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether this leave type is without pay',
  `isCarryForwardEnabled` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether unused leaves of this type can be carried forward',
  `isCarryForward` tinyint(1) NOT NULL DEFAULT '0',
  `countHolidaysAsLeave` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether holidays falling during this leave are counted as leave days',
  `includeHolidaysAsLeave` tinyint(1) NOT NULL DEFAULT '0',
  `maxConsecutiveLeaves` int DEFAULT '0' COMMENT 'Maximum consecutive days allowed for this leave type',
  `isLeaveWithoutPay` tinyint(1) NOT NULL DEFAULT '0',
  `isPartiallyPaidLeave` tinyint(1) NOT NULL DEFAULT '0',
  `isOptionalLeave` tinyint(1) NOT NULL DEFAULT '0',
  `allowNegativeBalance` tinyint(1) NOT NULL DEFAULT '0',
  `allowOverAllocation` tinyint(1) NOT NULL DEFAULT '0',
  `isCompensatory` tinyint(1) NOT NULL DEFAULT '0',
  `allowEncashment` tinyint(1) NOT NULL DEFAULT '0',
  `isEarnedLeave` tinyint(1) NOT NULL DEFAULT '0',
  `status` enum('Active','Inactive') NOT NULL DEFAULT 'Active',
  `companyId` int NOT NULL,
  `createdBy` varchar(255) DEFAULT NULL,
  `updatedBy` varchar(255) DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`leaveTypeId`),
  UNIQUE KEY `leaveTypeName` (`leaveTypeName`),
  UNIQUE KEY `leaveTypeName_2` (`leaveTypeName`),
  UNIQUE KEY `leaveTypeName_3` (`leaveTypeName`),
  KEY `companyId` (`companyId`),
  CONSTRAINT `leave_types_ibfk_1` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `leave_types`
--

LOCK TABLES `leave_types` WRITE;
/*!40000 ALTER TABLE `leave_types` DISABLE KEYS */;
/*!40000 ALTER TABLE `leave_types` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `permissions`
--

DROP TABLE IF EXISTS `permissions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `permissions` (
  `permissionId` int NOT NULL AUTO_INCREMENT,
  `staffId` int NOT NULL,
  `companyId` int NOT NULL,
  `attendanceId` int DEFAULT NULL,
  `permissionDate` date NOT NULL,
  `permissionHours` decimal(4,2) NOT NULL DEFAULT '0.00',
  `permissionStartTime` time DEFAULT NULL,
  `permissionEndTime` time DEFAULT NULL,
  `notes` text,
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`permissionId`),
  KEY `idx_permission_company_date` (`companyId`,`permissionDate`),
  KEY `idx_permission_staff_date` (`staffId`,`permissionDate`),
  KEY `attendanceId` (`attendanceId`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `permissions_ibfk_10` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `permissions_ibfk_6` FOREIGN KEY (`staffId`) REFERENCES `staff_details` (`staffId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `permissions_ibfk_7` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `permissions_ibfk_8` FOREIGN KEY (`attendanceId`) REFERENCES `attendance` (`attendanceId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `permissions_ibfk_9` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `permissions`
--

LOCK TABLES `permissions` WRITE;
/*!40000 ALTER TABLE `permissions` DISABLE KEYS */;
/*!40000 ALTER TABLE `permissions` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `reset_tokens`
--

DROP TABLE IF EXISTS `reset_tokens`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `reset_tokens` (
  `tokenId` int NOT NULL AUTO_INCREMENT,
  `userId` int NOT NULL COMMENT 'User associated with this reset token',
  `token` varchar(255) NOT NULL COMMENT 'Hashed password reset token',
  `expiresAt` datetime NOT NULL COMMENT 'Token expiration date and time',
  PRIMARY KEY (`tokenId`),
  KEY `idx_reset_user` (`userId`),
  KEY `idx_reset_token` (`token`),
  KEY `idx_reset_expiry` (`expiresAt`),
  CONSTRAINT `reset_tokens_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `reset_tokens`
--

LOCK TABLES `reset_tokens` WRITE;
/*!40000 ALTER TABLE `reset_tokens` DISABLE KEYS */;
/*!40000 ALTER TABLE `reset_tokens` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `roles`
--

DROP TABLE IF EXISTS `roles`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `roles` (
  `roleId` int NOT NULL AUTO_INCREMENT,
  `roleName` varchar(100) NOT NULL COMMENT 'Role name (e.g. "Staff", "Admin", "Department Admin")',
  `status` enum('Active','Inactive') NOT NULL DEFAULT 'Active',
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`roleId`),
  UNIQUE KEY `unique_role_name` (`roleName`),
  KEY `idx_role_status` (`status`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `roles_ibfk_1` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `roles_ibfk_2` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `roles`
--

LOCK TABLES `roles` WRITE;
/*!40000 ALTER TABLE `roles` DISABLE KEYS */;
/*!40000 ALTER TABLE `roles` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `salary_components`
--

DROP TABLE IF EXISTS `salary_components`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `salary_components` (
  `salaryComponentId` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL COMMENT 'Name of the salary component (e.g. "Basic Pay", "House Rent Allowance", "Professional Tax")',
  `description` text COMMENT 'Optional description shown in salary setup screens',
  `code` varchar(20) NOT NULL COMMENT 'Unique short code for this component (e.g. "BASIC", "HRA", "PF", "PT")',
  `type` enum('Earning','Deduction') NOT NULL COMMENT 'Whether this is an earning or deduction component',
  `calculationType` enum('Fixed','Percentage','Formula') NOT NULL DEFAULT 'Fixed' COMMENT 'How the amount is calculated',
  `percentage` decimal(5,2) DEFAULT NULL COMMENT 'Percentage value when calculationType is Percentage (e.g. 12 for 12%)',
  `percentageBase` varchar(20) DEFAULT NULL COMMENT 'Base component code when calculationType is Percentage (e.g. BASIC, GROSS)',
  `formula` text COMMENT 'Mathematical expression when calculationType is Formula (e.g. "BASIC * 0.12" or "(BASIC + DA) * 0.10")',
  `affectsGrossSalary` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Whether this component contributes to gross salary',
  `affectsNetSalary` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Whether this component affects take-home/net salary',
  `isTaxable` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Whether this component is subject to income tax',
  `isStatutory` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether this is a mandatory/statutory component (e.g. PF, ESI, PT)',
  `displayOrder` int NOT NULL DEFAULT '0' COMMENT 'Order in which this component appears in payslip',
  `status` enum('Active','Inactive') NOT NULL DEFAULT 'Active',
  `companyId` int NOT NULL,
  `createdBy` int DEFAULT NULL COMMENT 'User who created this salary component',
  `updatedBy` int DEFAULT NULL COMMENT 'User who last updated this salary component',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`salaryComponentId`),
  UNIQUE KEY `unique_code_per_company` (`code`,`companyId`),
  UNIQUE KEY `unique_name_per_company` (`name`,`companyId`),
  KEY `idx_company_status` (`companyId`,`status`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `salary_components_ibfk_4` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `salary_components_ibfk_5` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `salary_components_ibfk_6` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `salary_components`
--

LOCK TABLES `salary_components` WRITE;
/*!40000 ALTER TABLE `salary_components` DISABLE KEYS */;
/*!40000 ALTER TABLE `salary_components` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `salary_generation_details`
--

DROP TABLE IF EXISTS `salary_generation_details`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `salary_generation_details` (
  `salaryGenerationDetailId` int NOT NULL AUTO_INCREMENT,
  `salaryGenerationId` int NOT NULL,
  `companyId` int DEFAULT NULL,
  `componentId` int NOT NULL,
  `componentName` varchar(100) NOT NULL COMMENT 'Snapshot of component name at time of generation',
  `componentType` enum('Earning','Deduction') NOT NULL,
  `calculationType` enum('Fixed','Percentage','Formula') NOT NULL,
  `baseAmount` decimal(12,2) DEFAULT NULL COMMENT 'Base amount before any calculation/proration',
  `calculatedAmount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT 'Final calculated amount for this component',
  `isProrated` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether amount was prorated based on attendance/partial period',
  `proratedAmount` decimal(12,2) DEFAULT NULL COMMENT 'Amount after proration (if applicable)',
  `formula` text COMMENT 'Formula expression used (if calculationType is Formula)',
  `remarks` text COMMENT 'Any special remarks for this component instance',
  `createdBy` int DEFAULT NULL COMMENT 'User who created/recorded this detail',
  `updatedBy` int DEFAULT NULL COMMENT 'User who last updated this detail',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  `salaryComponentId` int DEFAULT NULL,
  PRIMARY KEY (`salaryGenerationDetailId`),
  UNIQUE KEY `unique_generation_component` (`salaryGenerationId`,`componentId`),
  KEY `idx_salary_generation` (`salaryGenerationId`),
  KEY `idx_salary_generation_company` (`companyId`),
  KEY `idx_component` (`componentId`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  KEY `salaryComponentId` (`salaryComponentId`),
  CONSTRAINT `salary_generation_details_ibfk_10` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `salary_generation_details_ibfk_11` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `salary_generation_details_ibfk_12` FOREIGN KEY (`salaryComponentId`) REFERENCES `salary_components` (`salaryComponentId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `salary_generation_details_ibfk_7` FOREIGN KEY (`salaryGenerationId`) REFERENCES `salary_generations` (`salaryGenerationId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `salary_generation_details_ibfk_8` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `salary_generation_details_ibfk_9` FOREIGN KEY (`componentId`) REFERENCES `salary_components` (`salaryComponentId`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `salary_generation_details`
--

LOCK TABLES `salary_generation_details` WRITE;
/*!40000 ALTER TABLE `salary_generation_details` DISABLE KEYS */;
/*!40000 ALTER TABLE `salary_generation_details` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `salary_generations`
--

DROP TABLE IF EXISTS `salary_generations`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `salary_generations` (
  `salaryGenerationId` int NOT NULL AUTO_INCREMENT,
  `staffId` int NOT NULL,
  `employeeSalaryMasterId` int NOT NULL COMMENT 'Reference to the salary structure used for this generation',
  `companyId` int NOT NULL,
  `salaryMonth` int NOT NULL COMMENT 'Month number (1-12)',
  `salaryYear` int NOT NULL COMMENT 'Year (e.g. 2025)',
  `payPeriodStart` date NOT NULL COMMENT 'Start date of the pay period',
  `payPeriodEnd` date NOT NULL COMMENT 'End date of the pay period',
  `workingDays` int NOT NULL DEFAULT '0' COMMENT 'Total working days in the pay period',
  `presentDays` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT 'Days present (includes half days as 0.5)',
  `absentDays` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT 'Days absent',
  `paidLeaveDays` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT 'Paid leave days taken',
  `unpaidLeaveDays` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT 'Unpaid leave days taken',
  `holidayDays` int NOT NULL DEFAULT '0' COMMENT 'Public holidays in the period',
  `weekOffDays` int NOT NULL DEFAULT '0' COMMENT 'Week offs in the period',
  `overtimeHours` decimal(6,2) NOT NULL DEFAULT '0.00' COMMENT 'Total overtime hours',
  `lateCount` int NOT NULL DEFAULT '0' COMMENT 'Number of late arrivals',
  `earlyExitCount` int NOT NULL DEFAULT '0' COMMENT 'Number of early exits',
  `basicSalary` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT 'Basic salary component',
  `totalEarnings` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT 'Sum of all earning components',
  `totalDeductions` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT 'Sum of all deduction components',
  `grossSalary` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT 'Total earnings before deductions',
  `netSalary` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT 'Final take-home salary (gross - deductions)',
  `overtimePay` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Additional pay for overtime',
  `lateDeduction` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Deduction for late arrivals',
  `absentDeduction` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Deduction for absences',
  `leaveDeduction` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Deduction for unpaid leaves',
  `bonus` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT 'Any bonus amount',
  `remarks` text COMMENT 'Additional notes or remarks',
  `status` enum('Draft','Generated','Approved','Paid','Cancelled') NOT NULL DEFAULT 'Draft' COMMENT 'Salary generation status',
  `generatedBy` int DEFAULT NULL,
  `approvedBy` int DEFAULT NULL,
  `approvedAt` datetime DEFAULT NULL,
  `paidBy` int DEFAULT NULL,
  `paidAt` datetime DEFAULT NULL,
  `paymentMethod` enum('Bank Transfer','Cash','Cheque','UPI','Other') DEFAULT NULL COMMENT 'Method of salary payment',
  `paymentReference` varchar(100) DEFAULT NULL COMMENT 'Transaction ID or reference number',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`salaryGenerationId`),
  UNIQUE KEY `unique_employee_pay_period` (`companyId`,`staffId`,`payPeriodStart`,`payPeriodEnd`),
  KEY `idx_company_month_year` (`companyId`,`salaryMonth`,`salaryYear`),
  KEY `idx_salary_status` (`status`),
  KEY `staffId` (`staffId`),
  KEY `employeeSalaryMasterId` (`employeeSalaryMasterId`),
  KEY `generatedBy` (`generatedBy`),
  KEY `approvedBy` (`approvedBy`),
  KEY `paidBy` (`paidBy`),
  CONSTRAINT `salary_generations_ibfk_10` FOREIGN KEY (`generatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `salary_generations_ibfk_11` FOREIGN KEY (`approvedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `salary_generations_ibfk_12` FOREIGN KEY (`paidBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `salary_generations_ibfk_7` FOREIGN KEY (`staffId`) REFERENCES `staff_details` (`staffId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `salary_generations_ibfk_8` FOREIGN KEY (`employeeSalaryMasterId`) REFERENCES `employee_salary_masters` (`employeeSalaryMasterId`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `salary_generations_ibfk_9` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `salary_generations`
--

LOCK TABLES `salary_generations` WRITE;
/*!40000 ALTER TABLE `salary_generations` DISABLE KEYS */;
/*!40000 ALTER TABLE `salary_generations` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `salary_revision_histories`
--

DROP TABLE IF EXISTS `salary_revision_histories`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `salary_revision_histories` (
  `salaryRevisionHistoryId` int NOT NULL AUTO_INCREMENT,
  `staffId` int NOT NULL,
  `companyId` int NOT NULL,
  `oldSalaryMasterId` int DEFAULT NULL COMMENT 'Previous salary structure (null for initial assignment)',
  `newSalaryMasterId` int NOT NULL COMMENT 'New salary structure',
  `revisionDate` date NOT NULL COMMENT 'Date when this revision becomes effective',
  `revisionType` enum('Initial','Annual_Hike','Promotion','Special_Increment','Correction','Transfer') NOT NULL,
  `oldBasicSalary` decimal(12,2) DEFAULT NULL COMMENT 'Previous basic salary',
  `newBasicSalary` decimal(12,2) NOT NULL COMMENT 'New basic salary',
  `oldGrossSalary` decimal(12,2) DEFAULT NULL COMMENT 'Previous gross salary',
  `newGrossSalary` decimal(12,2) NOT NULL COMMENT 'New gross salary',
  `oldCTC` decimal(12,2) DEFAULT NULL COMMENT 'Previous annual CTC',
  `newCTC` decimal(12,2) NOT NULL COMMENT 'New annual CTC',
  `incrementAmount` decimal(12,2) NOT NULL COMMENT 'Absolute increment amount',
  `incrementPercentage` decimal(5,2) NOT NULL COMMENT 'Percentage increase',
  `reason` text COMMENT 'Reason for this salary revision',
  `remarks` text,
  `approvedBy` int DEFAULT NULL COMMENT 'User who approved this revision',
  `approvedDate` datetime DEFAULT NULL,
  `processedBy` int DEFAULT NULL COMMENT 'User who processed/recorded this revision',
  `createdBy` int DEFAULT NULL COMMENT 'User who created this history record',
  `updatedBy` int DEFAULT NULL COMMENT 'User who last updated this history record',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`salaryRevisionHistoryId`),
  UNIQUE KEY `unique_employee_new_structure` (`staffId`,`newSalaryMasterId`),
  KEY `idx_employee_revision_date` (`staffId`,`revisionDate`),
  KEY `idx_revision_type` (`revisionType`),
  KEY `idx_company` (`companyId`),
  KEY `oldSalaryMasterId` (`oldSalaryMasterId`),
  KEY `newSalaryMasterId` (`newSalaryMasterId`),
  KEY `approvedBy` (`approvedBy`),
  KEY `processedBy` (`processedBy`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `salary_revision_histories_ibfk_10` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `salary_revision_histories_ibfk_11` FOREIGN KEY (`oldSalaryMasterId`) REFERENCES `employee_salary_masters` (`employeeSalaryMasterId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `salary_revision_histories_ibfk_12` FOREIGN KEY (`newSalaryMasterId`) REFERENCES `employee_salary_masters` (`employeeSalaryMasterId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `salary_revision_histories_ibfk_13` FOREIGN KEY (`approvedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `salary_revision_histories_ibfk_14` FOREIGN KEY (`processedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `salary_revision_histories_ibfk_15` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `salary_revision_histories_ibfk_16` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `salary_revision_histories_ibfk_9` FOREIGN KEY (`staffId`) REFERENCES `staff_details` (`staffId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `salary_revision_histories`
--

LOCK TABLES `salary_revision_histories` WRITE;
/*!40000 ALTER TABLE `salary_revision_histories` DISABLE KEYS */;
/*!40000 ALTER TABLE `salary_revision_histories` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `shift_assignments`
--

DROP TABLE IF EXISTS `shift_assignments`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `shift_assignments` (
  `shiftAssignmentId` int NOT NULL AUTO_INCREMENT,
  `staffId` int NOT NULL,
  `shiftTypeId` int NOT NULL,
  `startDate` date DEFAULT NULL COMMENT 'Start date for recurring shift assignments',
  `endDate` date DEFAULT NULL COMMENT 'End date for recurring shift assignments',
  `isRecurring` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether this assignment repeats over time',
  `recurringPattern` enum('daily','weekly','monthly','custom') DEFAULT NULL COMMENT 'Recurrence frequency pattern',
  `recurringDays` json DEFAULT NULL COMMENT 'Days of week for weekly pattern: [0,1,2,3,4,5,6] where 0=Sunday',
  `status` enum('Active','Inactive','Cancelled') NOT NULL DEFAULT 'Active',
  `notes` text COMMENT 'Additional notes or instructions for this shift assignment',
  `companyId` int NOT NULL,
  `createdBy` int DEFAULT NULL COMMENT 'User who created this shift assignment',
  `updatedBy` int DEFAULT NULL COMMENT 'User who last updated this shift assignment',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`shiftAssignmentId`),
  UNIQUE KEY `unique_employee_shift_assignment` (`staffId`),
  KEY `idx_company_status` (`companyId`,`status`),
  KEY `idx_shift_type` (`shiftTypeId`),
  KEY `idx_employee_status` (`staffId`,`status`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `shift_assignments_ibfk_10` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `shift_assignments_ibfk_6` FOREIGN KEY (`staffId`) REFERENCES `staff_details` (`staffId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `shift_assignments_ibfk_7` FOREIGN KEY (`shiftTypeId`) REFERENCES `shift_types` (`shiftTypeId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `shift_assignments_ibfk_8` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `shift_assignments_ibfk_9` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `shift_assignments`
--

LOCK TABLES `shift_assignments` WRITE;
/*!40000 ALTER TABLE `shift_assignments` DISABLE KEYS */;
/*!40000 ALTER TABLE `shift_assignments` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `shift_types`
--

DROP TABLE IF EXISTS `shift_types`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `shift_types` (
  `shiftTypeId` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL COMMENT 'Shift name (e.g. "General Shift", "Night Shift", "Morning Shift")',
  `startTime` time NOT NULL COMMENT 'Shift start time (e.g. "09:00:00")',
  `endTime` time NOT NULL COMMENT 'Shift end time (e.g. "18:00:00")',
  `beginCheckInBefore` int NOT NULL DEFAULT '15' COMMENT 'Minutes before shift start to allow check-in',
  `allowCheckOutAfter` int NOT NULL DEFAULT '15' COMMENT 'Minutes after shift end to allow check-out',
  `enableAutoAttendance` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Automatically mark attendance if no manual punch',
  `requireCheckIn` tinyint(1) NOT NULL DEFAULT '1',
  `requireCheckOut` tinyint(1) NOT NULL DEFAULT '1',
  `allowMultipleCheckIns` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Allow multiple check-ins/out per day',
  `autoMarkAbsentIfNoCheckIn` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Auto-mark absent if no check-in recorded',
  `workingHoursCalculation` enum('first_to_last','fixed_hours','with_breaks') NOT NULL DEFAULT 'first_to_last' COMMENT 'Method to calculate working hours',
  `minimumHours` decimal(4,2) NOT NULL DEFAULT '6.00' COMMENT 'Minimum working hours required to mark present',
  `halfDayHours` decimal(4,2) NOT NULL DEFAULT '4.00' COMMENT 'Working hours threshold for half day',
  `absentHours` decimal(4,2) NOT NULL DEFAULT '6.00' COMMENT 'Working hours threshold to mark absent',
  `enableLateEntry` tinyint(1) NOT NULL DEFAULT '1',
  `lateGracePeriod` int NOT NULL DEFAULT '15' COMMENT 'Grace period in minutes for late entry',
  `enableEarlyExit` tinyint(1) NOT NULL DEFAULT '1',
  `earlyExitPeriod` int NOT NULL DEFAULT '15' COMMENT 'Period in minutes for early exit allowance',
  `markAutoAttendanceOnHolidays` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Auto-mark attendance on holidays',
  `weeklyOff` text NOT NULL COMMENT 'JSON array of weekly off day names (e.g. ["sunday", "saturday"])',
  `status` enum('Active','Inactive') NOT NULL DEFAULT 'Active',
  `companyId` int NOT NULL,
  `createdBy` int DEFAULT NULL COMMENT 'User who created this shift type',
  `updatedBy` int DEFAULT NULL COMMENT 'User who last updated this shift type',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`shiftTypeId`),
  KEY `idx_company_status` (`companyId`,`status`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `shift_types_ibfk_4` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `shift_types_ibfk_5` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `shift_types_ibfk_6` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `shift_types`
--

LOCK TABLES `shift_types` WRITE;
/*!40000 ALTER TABLE `shift_types` DISABLE KEYS */;
/*!40000 ALTER TABLE `shift_types` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `staff_details`
--

DROP TABLE IF EXISTS `staff_details`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `staff_details` (
  `staffId` int NOT NULL AUTO_INCREMENT COMMENT 'Primary key for employee/staff',
  `biometricNumber` varchar(50) DEFAULT NULL COMMENT 'Biometric ID / Enrollment Number from device',
  `companyId` int NOT NULL,
  `staffNumber` varchar(255) NOT NULL COMMENT 'Reference to user table for login credentials',
  `salutation` varchar(10) DEFAULT NULL,
  `firstName` varchar(50) NOT NULL,
  `middleName` varchar(50) DEFAULT NULL,
  `lastName` varchar(50) DEFAULT NULL,
  `gender` enum('Male','Female','Other') DEFAULT NULL,
  `DOB` date DEFAULT NULL,
  `bloodGroup` enum('A+','A-','B+','B-','O+','O-','AB+','AB-') DEFAULT NULL,
  `maritalStatus` enum('Single','Married','Divorced','Widowed') DEFAULT NULL,
  `weddingDate` date DEFAULT NULL,
  `photo` varchar(500) DEFAULT NULL,
  `personalEmail` varchar(150) NOT NULL,
  `employeeMail` varchar(150) DEFAULT NULL,
  `mobileNumber` varchar(15) DEFAULT NULL,
  `alternateMobile` varchar(15) DEFAULT NULL,
  `emergencyContactName` varchar(100) DEFAULT NULL,
  `emergencyContactNumber` varchar(15) DEFAULT NULL,
  `emergencyContactRelationship` varchar(50) DEFAULT NULL,
  `currentAddressLine1` varchar(150) DEFAULT NULL,
  `currentAddressLine2` varchar(150) DEFAULT NULL,
  `currentCity` varchar(100) DEFAULT NULL,
  `currentState` varchar(100) DEFAULT NULL,
  `currentPincode` varchar(10) DEFAULT NULL,
  `currentCountry` varchar(100) DEFAULT 'India',
  `permanentAddressLine1` varchar(150) DEFAULT NULL,
  `permanentAddressLine2` varchar(150) DEFAULT NULL,
  `permanentCity` varchar(100) DEFAULT NULL,
  `permanentState` varchar(100) DEFAULT NULL,
  `permanentPincode` varchar(10) DEFAULT NULL,
  `permanentCountry` varchar(100) DEFAULT NULL,
  `departmentId` int NOT NULL,
  `roleId` int DEFAULT NULL COMMENT 'Role mapped from users.roleId',
  `designationId` int DEFAULT NULL,
  `employeeGradeId` int DEFAULT NULL,
  `DOJ` date NOT NULL,
  `confirmationDate` date DEFAULT NULL,
  `probationPeriod` int DEFAULT '0' COMMENT 'in months',
  `reportsTo` int DEFAULT NULL,
  `workLocation` varchar(100) DEFAULT NULL,
  `employmentStatus` enum('Active','Resigned','Terminated','On Leave','Retired','Notice Period') NOT NULL DEFAULT 'Active',
  `shiftTypeId` int DEFAULT NULL,
  `leavePolicyId` int DEFAULT NULL,
  `isOvertimeApplicable` tinyint(1) DEFAULT '0',
  `remainingPermissionHours` int DEFAULT '0',
  `basicSalary` decimal(12,2) DEFAULT NULL,
  `costToCompany` decimal(15,2) DEFAULT NULL,
  `salaryCurrency` varchar(3) DEFAULT 'INR',
  `paymentMode` enum('Bank Transfer','Cash','Cheque') DEFAULT 'Bank Transfer',
  `bankName` varchar(100) DEFAULT NULL,
  `bankAccountNumber` varchar(50) DEFAULT NULL,
  `ifscCode` varchar(11) DEFAULT NULL,
  `panNumber` varchar(10) DEFAULT NULL,
  `uanNumber` varchar(20) DEFAULT NULL,
  `esiNumber` varchar(20) DEFAULT NULL,
  `isTransportRequired` tinyint(1) DEFAULT '0',
  `busId` int DEFAULT NULL,
  `pickupPoint` varchar(150) DEFAULT NULL,
  `aadhaarNumber` varchar(12) DEFAULT NULL,
  `passportNumber` varchar(20) DEFAULT NULL,
  `drivingLicenseNumber` varchar(20) DEFAULT NULL,
  `voterIdNumber` varchar(20) DEFAULT NULL,
  `annaUniversityFacultyId` varchar(100) DEFAULT NULL COMMENT 'Anna University Faculty ID',
  `aicteFacultyId` varchar(100) DEFAULT NULL COMMENT 'AICTE Faculty ID',
  `orcid` varchar(100) DEFAULT NULL COMMENT 'ORCID - Open Researcher and Contributor ID',
  `researcherId` varchar(100) DEFAULT NULL COMMENT 'ResearcherID (Web of Science/Publons)',
  `googleScholarId` varchar(100) DEFAULT NULL COMMENT 'Google Scholar Profile ID',
  `scopusProfile` varchar(255) DEFAULT NULL COMMENT 'Scopus Profile URL or ID',
  `vidwanProfile` varchar(255) DEFAULT NULL COMMENT 'VIDWAN Profile URL or ID',
  `supervisorId` int DEFAULT NULL COMMENT 'Academic/Research Supervisor',
  `hIndex` int DEFAULT NULL COMMENT 'h-index for research publications',
  `citationIndex` int DEFAULT NULL COMMENT 'Total citation count',
  `resignationLetterDate` date DEFAULT NULL,
  `reasonForResignation` text COMMENT 'Reason provided for resignation',
  `relievingDate` date DEFAULT NULL,
  `dateOfRetirement` date DEFAULT NULL COMMENT 'Auto-calculated based on DOB + retirement age from settings (default 58 years)',
  `exitInterviewHeldOn` date DEFAULT NULL,
  `status` enum('Active','Inactive') NOT NULL DEFAULT 'Active',
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `deletedAt` datetime DEFAULT NULL,
  `biometricDeviceId` int DEFAULT NULL,
  `gradeId` int DEFAULT NULL,
  PRIMARY KEY (`staffId`),
  UNIQUE KEY `biometricNumber` (`biometricNumber`),
  UNIQUE KEY `biometricNumber_2` (`biometricNumber`),
  UNIQUE KEY `biometricNumber_3` (`biometricNumber`),
  KEY `companyId` (`companyId`),
  KEY `staffNumber` (`staffNumber`),
  KEY `departmentId` (`departmentId`),
  KEY `roleId` (`roleId`),
  KEY `designationId` (`designationId`),
  KEY `employeeGradeId` (`employeeGradeId`),
  KEY `reportsTo` (`reportsTo`),
  KEY `shiftTypeId` (`shiftTypeId`),
  KEY `leavePolicyId` (`leavePolicyId`),
  KEY `busId` (`busId`),
  KEY `supervisorId` (`supervisorId`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  KEY `biometricDeviceId` (`biometricDeviceId`),
  KEY `gradeId` (`gradeId`),
  CONSTRAINT `staff_details_ibfk_16` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `staff_details_ibfk_17` FOREIGN KEY (`staffNumber`) REFERENCES `users` (`userNumber`) ON UPDATE CASCADE,
  CONSTRAINT `staff_details_ibfk_18` FOREIGN KEY (`departmentId`) REFERENCES `departments` (`departmentId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `staff_details_ibfk_19` FOREIGN KEY (`roleId`) REFERENCES `roles` (`roleId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `staff_details_ibfk_20` FOREIGN KEY (`designationId`) REFERENCES `designations` (`designationId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `staff_details_ibfk_21` FOREIGN KEY (`employeeGradeId`) REFERENCES `employee_grades` (`employeeGradeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `staff_details_ibfk_22` FOREIGN KEY (`reportsTo`) REFERENCES `staff_details` (`staffId`),
  CONSTRAINT `staff_details_ibfk_23` FOREIGN KEY (`shiftTypeId`) REFERENCES `shift_types` (`shiftTypeId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `staff_details_ibfk_24` FOREIGN KEY (`leavePolicyId`) REFERENCES `leave_policies` (`leavePolicyId`),
  CONSTRAINT `staff_details_ibfk_25` FOREIGN KEY (`busId`) REFERENCES `buses` (`busId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `staff_details_ibfk_26` FOREIGN KEY (`supervisorId`) REFERENCES `staff_details` (`staffId`),
  CONSTRAINT `staff_details_ibfk_27` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `staff_details_ibfk_28` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `staff_details_ibfk_29` FOREIGN KEY (`biometricDeviceId`) REFERENCES `biometric_devices` (`deviceId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `staff_details_ibfk_30` FOREIGN KEY (`gradeId`) REFERENCES `employee_grades` (`employeeGradeId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `staff_details`
--

LOCK TABLES `staff_details` WRITE;
/*!40000 ALTER TABLE `staff_details` DISABLE KEYS */;
/*!40000 ALTER TABLE `staff_details` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `student_details`
--

DROP TABLE IF EXISTS `student_details`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `student_details` (
  `studentId` int NOT NULL AUTO_INCREMENT,
  `studentName` varchar(50) NOT NULL,
  `registerNumber` varchar(50) NOT NULL,
  `departmentId` int DEFAULT NULL,
  `batch` int DEFAULT NULL,
  `semester` varchar(255) DEFAULT NULL,
  `companyId` int NOT NULL,
  `staffId` int DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `dateOfJoining` datetime DEFAULT NULL,
  `dateOfBirth` datetime DEFAULT NULL,
  `bloodGroup` enum('A+','A-','B+','B-','O+','O-','AB+','AB-') DEFAULT NULL,
  `tutorEmail` varchar(255) DEFAULT NULL,
  `personalEmail` varchar(255) DEFAULT NULL,
  `firstGraduate` enum('Yes','No') DEFAULT NULL,
  `aadharCardNo` varchar(12) DEFAULT NULL,
  `studentType` enum('Day-Scholar','Hosteller') DEFAULT NULL,
  `motherTongue` varchar(255) DEFAULT NULL,
  `identificationMark` varchar(255) DEFAULT NULL,
  `religion` enum('Hindu','Muslim','Christian','Others') DEFAULT NULL,
  `caste` varchar(255) DEFAULT NULL,
  `community` enum('General','OBC','SC','ST','Others') DEFAULT NULL,
  `gender` enum('Male','Female','Transgender') DEFAULT NULL,
  `seatType` enum('Counselling','Management') DEFAULT NULL,
  `section` varchar(255) DEFAULT NULL,
  `doorNo` varchar(255) DEFAULT NULL,
  `street` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `pincode` varchar(6) DEFAULT NULL,
  `personalPhone` varchar(10) DEFAULT NULL,
  `status` enum('Active','Inactive') NOT NULL DEFAULT 'Active',
  `pending` tinyint(1) DEFAULT '1',
  `tutorApprovalStatus` tinyint(1) DEFAULT '0',
  `approved_by` int DEFAULT NULL,
  `approvedAt` datetime DEFAULT NULL,
  `messages` json DEFAULT NULL,
  `skillrackProfile` varchar(255) DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`studentId`),
  UNIQUE KEY `registerNumber` (`registerNumber`),
  UNIQUE KEY `aadharCardNo` (`aadharCardNo`),
  UNIQUE KEY `aadharCardNo_2` (`aadharCardNo`),
  UNIQUE KEY `aadharCardNo_3` (`aadharCardNo`),
  KEY `departmentId` (`departmentId`),
  KEY `companyId` (`companyId`),
  KEY `staffId` (`staffId`),
  KEY `created_by` (`created_by`),
  KEY `updated_by` (`updated_by`),
  KEY `approved_by` (`approved_by`),
  CONSTRAINT `student_details_ibfk_10` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON DELETE CASCADE,
  CONSTRAINT `student_details_ibfk_11` FOREIGN KEY (`staffId`) REFERENCES `staff_details` (`staffId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `student_details_ibfk_12` FOREIGN KEY (`created_by`) REFERENCES `users` (`userId`) ON UPDATE CASCADE,
  CONSTRAINT `student_details_ibfk_13` FOREIGN KEY (`updated_by`) REFERENCES `users` (`userId`) ON UPDATE CASCADE,
  CONSTRAINT `student_details_ibfk_14` FOREIGN KEY (`approved_by`) REFERENCES `staff_details` (`staffId`) ON UPDATE CASCADE,
  CONSTRAINT `student_details_ibfk_8` FOREIGN KEY (`registerNumber`) REFERENCES `users` (`userNumber`),
  CONSTRAINT `student_details_ibfk_9` FOREIGN KEY (`departmentId`) REFERENCES `departments` (`departmentId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `student_details`
--

LOCK TABLES `student_details` WRITE;
/*!40000 ALTER TABLE `student_details` DISABLE KEYS */;
/*!40000 ALTER TABLE `student_details` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `users` (
  `userId` int NOT NULL AUTO_INCREMENT,
  `companyId` int NOT NULL DEFAULT '0',
  `departmentId` int DEFAULT NULL,
  `userNumber` varchar(255) NOT NULL,
  `userName` varchar(255) DEFAULT NULL,
  `userMail` varchar(255) NOT NULL,
  `roleId` int NOT NULL,
  `password` varchar(255) NOT NULL,
  `status` enum('Active','Inactive') DEFAULT 'Active',
  `createdBy` int DEFAULT NULL,
  `updatedBy` int DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE KEY `userNumber` (`userNumber`),
  UNIQUE KEY `userMail` (`userMail`),
  UNIQUE KEY `userNumber_2` (`userNumber`),
  UNIQUE KEY `userMail_2` (`userMail`),
  UNIQUE KEY `userNumber_3` (`userNumber`),
  UNIQUE KEY `userMail_3` (`userMail`),
  KEY `companyId` (`companyId`),
  KEY `departmentId` (`departmentId`),
  KEY `roleId` (`roleId`),
  KEY `createdBy` (`createdBy`),
  KEY `updatedBy` (`updatedBy`),
  CONSTRAINT `users_ibfk_10` FOREIGN KEY (`updatedBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `users_ibfk_6` FOREIGN KEY (`companyId`) REFERENCES `companies` (`companyId`) ON UPDATE CASCADE,
  CONSTRAINT `users_ibfk_7` FOREIGN KEY (`departmentId`) REFERENCES `departments` (`departmentId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `users_ibfk_8` FOREIGN KEY (`roleId`) REFERENCES `roles` (`roleId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `users_ibfk_9` FOREIGN KEY (`createdBy`) REFERENCES `users` (`userId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `users`
--

LOCK TABLES `users` WRITE;
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
/*!40000 ALTER TABLE `users` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2026-07-03 14:24:04
