const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
  const Attendance = sequelize.define('Attendance', {
    attendanceId: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },

    staffId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: 'staff_details',
        key: 'staffId',
      },
      onDelete: 'CASCADE',
    },

    companyId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: 'companies',
        key: 'companyId',
      },
      onDelete: 'CASCADE',
    },

    // Shift related
    shiftAssignmentId: {
      type: DataTypes.INTEGER,
      allowNull: true,
      references: {
        model: 'shift_assignments',
        key: 'shiftAssignmentId',
      },
      onDelete: 'SET NULL',
    },

    shiftTypeId: {
      type: DataTypes.INTEGER,
      allowNull: true,
      references: {
        model: 'shift_types',
        key: 'shiftTypeId',
      },
      onDelete: 'SET NULL',
    },

    // Core attendance fields
    attendanceDate: {
      type: DataTypes.DATEONLY,
      allowNull: false,
    },

    scheduledStartTime: {
      type: DataTypes.TIME,
      allowNull: true,
      comment: 'Scheduled shift start time',
    },

    scheduledEndTime: {
      type: DataTypes.TIME,
      allowNull: true,
      comment: 'Scheduled shift end time',
    },

    firstCheckIn: {
      type: DataTypes.DATE,
      allowNull: true,
      comment: 'First actual check-in timestamp',
    },

    lastCheckOut: {
      type: DataTypes.DATE,
      allowNull: true,
      comment: 'Last actual check-out timestamp',
    },

    // Time & calculation fields
    totalCheckIns: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0,
    },

    totalCheckOuts: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0,
    },

    workingHours: {
      type: DataTypes.DECIMAL(5, 2),
      allowNull: true,
      comment: 'Calculated effective working hours',
    },

    breakHours: {
      type: DataTypes.DECIMAL(5, 2),
      allowNull: true,
      defaultValue: 0.00,
    },

    overtimeHours: {
      type: DataTypes.DECIMAL(5, 2),
      allowNull: true,
      defaultValue: 0.00,
    },

    // Status & flags
    attendanceStatus: {
      type: DataTypes.ENUM(
        'Present',
        'Absent',
        'Half-Day',
        'Late',
        'Early Exit',
        'Leave',
        'Holiday',
        'Week Off',
        'Permission'
      ),
      allowNull: false,
      defaultValue: 'Present',
    },

    isLate: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
    },

    lateByMinutes: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
    },

    isEarlyExit: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
    },

    earlyExitMinutes: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
    },

    isHoliday: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
    },

    isWeekOff: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
    },

    // Metadata
    autoGenerated: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
      comment: 'Auto-generated by system (e.g. default absent)',
    },

    remarks: {
      type: DataTypes.TEXT,
      allowNull: true,
    },

    approvedBy: {
      type: DataTypes.INTEGER,
      allowNull: true,
      references: {
        model: 'users',
        key: 'userId',
      },
      onDelete: 'SET NULL',
    },

    approvedAt: {
      type: DataTypes.DATE,
      allowNull: true,
    },

    createdBy: {
      type: DataTypes.INTEGER,
      allowNull: true,
      references: {
        model: 'users',
        key: 'userId',
      },
      onDelete: 'SET NULL',
    },

    updatedBy: {
      type: DataTypes.INTEGER,
      allowNull: true,
      references: {
        model: 'users',
        key: 'userId',
      },
      onDelete: 'SET NULL',
    },

  }, {
    tableName: 'attendance',
    timestamps: true,
    paranoid: true, // soft delete support

    indexes: [
      {
        unique: true,
        fields: ['staffId', 'attendanceDate'],
        name: 'unique_employee_attendance_date',
      },
      {
        fields: ['companyId', 'attendanceDate'],
        name: 'idx_company_attendance_date',
      },
      {
        fields: ['attendanceStatus'],
        name: 'idx_attendance_status',
      },
      {
        fields: ['shiftTypeId'],
        name: 'idx_shift_type',
      },
      {
        fields: ['approvedBy'],
        name: 'idx_approved_by',
      },
    ],
  });

  // Associations
  Attendance.associate = (models) => {
    Attendance.belongsTo(models.Employee, {
      foreignKey: 'staffId',
      as: 'employee',
    });

    Attendance.belongsTo(models.Company, {
      foreignKey: 'companyId',
      as: 'company',
    });

    Attendance.belongsTo(models.ShiftType, {
      foreignKey: 'shiftTypeId',
      as: 'shiftType',
    });

    Attendance.belongsTo(models.ShiftAssignment, {
      foreignKey: 'shiftAssignmentId',
      as: 'shiftAssignment',
    });

    Attendance.belongsTo(models.User, {
      foreignKey: 'approvedBy',
      as: 'approver',
    });

    Attendance.belongsTo(models.User, {
      foreignKey: 'createdBy',
      as: 'creator',
    });

    Attendance.belongsTo(models.User, {
      foreignKey: 'updatedBy',
      as: 'updater',
    });
  };

  // // Development sync (optional)
  // if (process.env.NODE_ENV === 'development') {
  //   Attendance.sync({ alter: true })
  //     .then(() => console.log('Attendance table synced successfully'))
  //     .catch(err => console.error('Error syncing Attendance table:', err));
  // }

  return Attendance;
};